### ISSUE TITLE
Настройка аналитики

### ISSUE THREAD

**Issue by moskovka** [htmlacademy/liga#1]
@tsergeytovarov зарегистрируйся тут https://tagmanager.google.com/;
поставь GTM на сайт;
дай доступ на: amoskovka@gmail.com, benann961@gmail.com, dwarfman@gmail.com;
удали коды счётчиков GA и YM из кода сайта.

**Comment by tsergeytovarov** [comment]
@moskovka проверь, я всё поставил.
