### ISSUE TITLE
Добавить текущее состояние браузерам

### ISSUE THREAD

**Issue by pepelsbey** [htmlacademy/liga#7]
Сразу после загрузки, все мобильные версии крутятся при наведении, а десктопная нет. На десктопную нужно переключиться. Как это и почему с виду не понятно. Десктопная достаточно большая, чтобы казалось — мол, наведу и должно. Но не крутится.

Конечно курсор (будь он проклят, я ожидал ссылку) помогает понять, что можно типа переключиться, но не сильно. Нужно следующее:

1. Состояние не только по наведению, но и активное. Чтобы мобильный браузер был с активной рамкой, которая показывает «её можно крутить». А когда кликнули на десктоп — у него появилась активная рамка.
2. Мало сделать мобильный браузер с рамкой, нужно ещё показать, что десктопная неактивная: полупрозрачность, размытость, чёрно-белость, что-то такое, чтобы было понятно: кликни меня и сможешь посмотреть и покрутить.

**Comment by tsergeytovarov** [comment]
Вадим, спасибо. Придумаем что-то, я переношу себе в репу это.
