### ISSUE TITLE
Подчеркивание у иконок в разделе "Как мы работаем"

### ISSUE THREAD

**Issue by AntonovIgor** [htmlacademy/liga#8]
Сегодня увидел странные подчеркивания у некоторых иконок - https://yadi.sk/i/09zXghmW3ZjhEq. Подчеркивания у 2, 3 и пятой иконок. Проявляется только в Chrome (Win7 x64, 68.0.3440.75). 

Подчеркивания у иконок в разделе "Как мы работаем".

**Comment by tsergeytovarov** [comment]
Спасибо, мы заблрали себе.
